In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../ai_medreview/data/data_v4.csv')

In [3]:
data.head()

,submission_id,respondent-id,time,rating,rating_score,surgery,pcn,review,review_len,review_PER,...,jev_actionability_confidence,jev_urgency,jev_urgency_confidence,jev_clinical_safety_concern,jev_clinical_safety_score,jev_dignity_or_inclusion_concern,jev_dignity_or_inclusion_score,jev_leaving_risk,jev_leaving_risk_score,source_sheet_row
0,eqgZOj0,RGPV0Ll,2026-01-01 01:33:05,Very good,5.0,The-Good-Practice,Brompton-Health-PCN,Sensitive informative timely No it was more th...,12,NaN,...,0.96,0.0,0.20,False,0.02,False,0.07,False,0.03,NaN
1,2E9jX2b,D4zMq7j,2026-01-01 12:09:08,Good,4.0,The-Good-Practice,Brompton-Health-PCN,It s the way they care for their patients and ...,17,NaN,...,1.00,0.0,0.99,False,0.02,False,0.02,False,0.02,NaN
2,9qANZNG,2EP7Xxb,2026-01-01 12:21:05,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,The doctor was checking the prescription with ...,30,NaN,...,0.97,0.0,0.96,False,0.03,False,0.42,False,0.03,NaN
3,b51ZWEo,772eL2,2026-01-01 12:30:16,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,I spoke to a kind girl initially who listened ...,44,NaN,...,0.84,0.0,0.74,False,0.05,False,0.05,False,0.06,NaN
4,dWJbd9o,1AV6kB4,2026-01-01 12:32:56,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,Because the response was very fast Not really ...,21,NaN,...,0.98,0.0,0.97,False,0.01,False,0.01,False,0.02,NaN

In [4]:
data['time'] =  pd.to_datetime(data['time'], format='mixed')

In [5]:
data.head()

,submission_id,respondent-id,time,rating,rating_score,surgery,pcn,review,review_len,review_PER,...,jev_actionability_confidence,jev_urgency,jev_urgency_confidence,jev_clinical_safety_concern,jev_clinical_safety_score,jev_dignity_or_inclusion_concern,jev_dignity_or_inclusion_score,jev_leaving_risk,jev_leaving_risk_score,source_sheet_row
0,eqgZOj0,RGPV0Ll,2026-01-01 01:33:05,Very good,5.0,The-Good-Practice,Brompton-Health-PCN,Sensitive informative timely No it was more th...,12,NaN,...,0.96,0.0,0.20,False,0.02,False,0.07,False,0.03,NaN
1,2E9jX2b,D4zMq7j,2026-01-01 12:09:08,Good,4.0,The-Good-Practice,Brompton-Health-PCN,It s the way they care for their patients and ...,17,NaN,...,1.00,0.0,0.99,False,0.02,False,0.02,False,0.02,NaN
2,9qANZNG,2EP7Xxb,2026-01-01 12:21:05,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,The doctor was checking the prescription with ...,30,NaN,...,0.97,0.0,0.96,False,0.03,False,0.42,False,0.03,NaN
3,b51ZWEo,772eL2,2026-01-01 12:30:16,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,I spoke to a kind girl initially who listened ...,44,NaN,...,0.84,0.0,0.74,False,0.05,False,0.05,False,0.06,NaN
4,dWJbd9o,1AV6kB4,2026-01-01 12:32:56,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,Because the response was very fast Not really ...,21,NaN,...,0.98,0.0,0.97,False,0.01,False,0.01,False,0.02,NaN

In [6]:
data[data['time'] == pd.to_datetime('2026-01-01')]

Empty DataFrame
Columns: [submission_id, respondent-id, time, rating, rating_score, surgery, pcn, review, review_len, review_PER, review_uid, jev_sentiment, jev_sentiment_confidence, jev_primary_topic, jev_primary_topic_confidence, jev_secondary_topics, jev_topic_probabilities, jev_staff_group, jev_staff_group_confidence, jev_sentiment_strength, jev_sentiment_strength_confidence, jev_actionability, jev_actionability_confidence, jev_urgency, jev_urgency_confidence, jev_clinical_safety_concern, jev_clinical_safety_score, jev_dignity_or_inclusion_concern, jev_dignity_or_inclusion_score, jev_leaving_risk, jev_leaving_risk_score, source_sheet_row]
Index: []

[0 rows x 32 columns]

In [8]:
import pandas as pd

data["time"] = pd.to_datetime(data["time"], errors="coerce")

# Get all entries on 8 December 2026, regardless of time
filtered_df = data.loc[
    (data["time"] >= "2026-11-08") &
    (data["time"] < "2026-11-09")
].copy()

filtered_df

,submission_id,respondent-id,time,rating,rating_score,surgery,pcn,review,review_len,review_PER,...,jev_actionability_confidence,jev_urgency,jev_urgency_confidence,jev_clinical_safety_concern,jev_clinical_safety_score,jev_dignity_or_inclusion_concern,jev_dignity_or_inclusion_score,jev_leaving_risk,jev_leaving_risk_score,source_sheet_row
3830,NaN,NaN,2026-11-08 11:52:00,Good,4.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,Update regarding the appointment delay while p...,10,NaN,...,0.30,2.0,0.51,False,0.18,False,0.06,False,0.09,NaN
3831,NaN,NaN,2026-11-08 15:09:00,Very good,5.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,I had run out of atorvatin not Ramipril but on...,20,NaN,...,0.34,2.0,0.49,False,0.42,False,0.02,False,0.06,NaN

In [9]:
mask = (data["time"] >= "2026-11-08") & (data["time"] < "2026-11-09")
df = data.loc[~mask].copy()

In [10]:
df.to_csv('../ai_medreview/data/data_v4.csv', index=False)