In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('../ai_medreview/data/data_v4.csv')

In [4]:
data.head()

,submission_id,respondent-id,time,rating,rating_score,surgery,pcn,review,review_len,review_PER,...,jev_actionability_confidence,jev_urgency,jev_urgency_confidence,jev_clinical_safety_concern,jev_clinical_safety_score,jev_dignity_or_inclusion_concern,jev_dignity_or_inclusion_score,jev_leaving_risk,jev_leaving_risk_score,source_sheet_row
0,eqgZOj0,RGPV0Ll,2026-01-01 01:33:05,Very good,5.0,The-Good-Practice,Brompton-Health-PCN,Sensitive informative timely No it was more th...,12,NaN,...,0.96,0.0,0.20,False,0.02,False,0.07,False,0.03,NaN
1,2E9jX2b,D4zMq7j,2026-01-01 12:09:08,Good,4.0,The-Good-Practice,Brompton-Health-PCN,It s the way they care for their patients and ...,17,NaN,...,1.00,0.0,0.99,False,0.02,False,0.02,False,0.02,NaN
2,9qANZNG,2EP7Xxb,2026-01-01 12:21:05,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,The doctor was checking the prescription with ...,30,NaN,...,0.97,0.0,0.96,False,0.03,False,0.42,False,0.03,NaN
3,b51ZWEo,772eL2,2026-01-01 12:30:16,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,I spoke to a kind girl initially who listened ...,44,NaN,...,0.84,0.0,0.74,False,0.05,False,0.05,False,0.06,NaN
4,dWJbd9o,1AV6kB4,2026-01-01 12:32:56,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,Because the response was very fast Not really ...,21,NaN,...,0.98,0.0,0.97,False,0.01,False,0.01,False,0.02,NaN

In [6]:
data['time'] =  pd.to_datetime(data['time'], format='mixed')

In [7]:
data.head()

,submission_id,respondent-id,time,rating,rating_score,surgery,pcn,review,review_len,review_PER,...,jev_actionability_confidence,jev_urgency,jev_urgency_confidence,jev_clinical_safety_concern,jev_clinical_safety_score,jev_dignity_or_inclusion_concern,jev_dignity_or_inclusion_score,jev_leaving_risk,jev_leaving_risk_score,source_sheet_row
0,eqgZOj0,RGPV0Ll,2026-01-01 01:33:05,Very good,5.0,The-Good-Practice,Brompton-Health-PCN,Sensitive informative timely No it was more th...,12,NaN,...,0.96,0.0,0.20,False,0.02,False,0.07,False,0.03,NaN
1,2E9jX2b,D4zMq7j,2026-01-01 12:09:08,Good,4.0,The-Good-Practice,Brompton-Health-PCN,It s the way they care for their patients and ...,17,NaN,...,1.00,0.0,0.99,False,0.02,False,0.02,False,0.02,NaN
2,9qANZNG,2EP7Xxb,2026-01-01 12:21:05,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,The doctor was checking the prescription with ...,30,NaN,...,0.97,0.0,0.96,False,0.03,False,0.42,False,0.03,NaN
3,b51ZWEo,772eL2,2026-01-01 12:30:16,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,I spoke to a kind girl initially who listened ...,44,NaN,...,0.84,0.0,0.74,False,0.05,False,0.05,False,0.06,NaN
4,dWJbd9o,1AV6kB4,2026-01-01 12:32:56,Very good,5.0,Health-Partners-at-Violet-Melchett,Brompton-Health-PCN,Because the response was very fast Not really ...,21,NaN,...,0.98,0.0,0.97,False,0.01,False,0.01,False,0.02,NaN

In [15]:
data[data['time'] == pd.to_datetime('2026-01-01')]

Empty DataFrame
Columns: [submission_id, respondent-id, time, rating, rating_score, surgery, pcn, review, review_len, review_PER, review_uid, jev_sentiment, jev_sentiment_confidence, jev_primary_topic, jev_primary_topic_confidence, jev_secondary_topics, jev_topic_probabilities, jev_staff_group, jev_staff_group_confidence, jev_sentiment_strength, jev_sentiment_strength_confidence, jev_actionability, jev_actionability_confidence, jev_urgency, jev_urgency_confidence, jev_clinical_safety_concern, jev_clinical_safety_score, jev_dignity_or_inclusion_concern, jev_dignity_or_inclusion_score, jev_leaving_risk, jev_leaving_risk_score, source_sheet_row]
Index: []

[0 rows x 32 columns]

In [17]:
import pandas as pd

data["time"] = pd.to_datetime(data["time"], errors="coerce")

# Get all entries on 8 December 2026, regardless of time
filtered_df = data.loc[
    (data["time"] >= "2026-12-08") &
    (data["time"] < "2026-12-09")
].copy()

filtered_df

,submission_id,respondent-id,time,rating,rating_score,surgery,pcn,review,review_len,review_PER,...,jev_actionability_confidence,jev_urgency,jev_urgency_confidence,jev_clinical_safety_concern,jev_clinical_safety_score,jev_dignity_or_inclusion_concern,jev_dignity_or_inclusion_score,jev_leaving_risk,jev_leaving_risk_score,source_sheet_row
3829,NaN,NaN,2026-12-08 16:00:00,Good,4.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,Advised two tablets required to change treatme...,15,NaN,...,0.86,2.0,0.72,True,0.62,False,0.02,False,0.11,NaN
3830,NaN,NaN,2026-12-08 16:00:00,Good,4.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,A bit more friendliness smile beyond decent pr...,8,NaN,...,0.48,0.0,0.85,False,0.01,False,0.06,False,0.06,NaN
3831,NaN,NaN,2026-12-08 16:00:00,Neither good nor poor,3.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,Less wait for appointment from day of booking ...,16,NaN,...,0.70,0.0,0.89,False,0.02,False,0.01,False,0.02,NaN
3832,NaN,NaN,2026-12-08 16:00:00,Very good,5.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,No improvement Very helpful and quick follow u...,9,NaN,...,0.38,0.0,0.21,False,0.07,False,0.02,False,0.09,NaN
3833,NaN,NaN,2026-12-08 16:00:00,Very good,5.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,Canâ€™t think of anything pertaining to my las...,9,NaN,...,0.97,0.0,0.86,False,0.02,False,0.02,False,0.07,NaN
3834,NaN,NaN,2026-12-08 16:00:00,Good,4.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,Gap to receipt altered tabs from dr PERSON Hav...,12,['Reddy'],...,0.00,1.0,0.00,False,0.10,False,0.10,False,0.04,NaN
3835,NaN,NaN,2026-12-08 16:00:00,Good,4.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,Very approachable and nice people i really imp...,8,NaN,...,1.00,0.0,0.98,False,0.01,False,0.02,False,0.02,NaN
3836,NaN,NaN,2026-12-08 16:00:00,Very good,5.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,Canâ€™t really think of anything besides perha...,14,NaN,...,0.43,0.0,0.70,False,0.02,False,0.05,False,0.05,NaN
3837,NaN,NaN,2026-12-08 16:00:00,Very good,5.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,The staff are very kind and polite The repeat ...,12,NaN,...,1.00,0.0,0.99,False,0.02,False,0.02,False,0.02,NaN
3838,NaN,NaN,2026-12-08 16:00:00,Very good,5.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,I marked â€œ excellent â€œ so no need to add more,11,NaN,...,1.00,0.0,0.99,False,0.01,False,0.01,False,0.02,NaN
3839,NaN,NaN,2026-12-08 16:00:00,Good,4.0,Scarsdale-Medical-Centre,Brompton-Health-PCN,For me it was perfect from all their dealings,9,NaN,...,1.00,0.0,0.99,False,0.01,False,0.01,False,0.02,NaN

In [18]:
mask = (data["time"] >= "2026-12-08") & (data["time"] < "2026-12-09")
df = data.loc[~mask].copy()

In [19]:
df.to_csv('../ai_medreview/data/data_v4.csv', index=False)